# Generated by Django 4.1.4 on 2023-02-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='gfg', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
